import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import StoreProvider from "@/providers/StoreProvider";
import { SidebarProvider } from "@/contexts/SidebarContext";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "900", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Tokyo Life",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className}  antialiased `}>
        <ThemeProvider>
          <AntdRegistry>
            <SidebarProvider>
              <StoreProvider>
                <ReactQueryProvider>
                  {children}
                  <ToastContainer />
                </ReactQueryProvider>
              </StoreProvider>
            </SidebarProvider>
          </AntdRegistry>
        </ThemeProvider>
      </body>
    </html>
  );
}
