export const QUERY_KEYS = {
  USER: "user",
  USERS: "users",
  REVIEWS: "reviews",
  PRODUCTS: "products",
  CATEGORIES: "categories",
  USER_ADDRESSES: "user-addresses",
  CARTS: "carts",
  ORDERS: "orders",
  ORDER: (orderCode: string) => `order-${orderCode}`,
  PRODUCT: (id: string | number) => `product-${id}`,
  SHIPPING: "shipping",
  PAYMENT: "payment",
  NOTIFICATIONS: "notifications",
  CONVERSATIONS: "conversations",
  CHAT_MESSAGES: "chat-messages",
  AI_CONVERSATIONS: "ai-conversations",
};
